services:
  - type: web
    name: cardapio-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    branch: main
    healthCheckPath: /
