name: Gerar Cardápio Araranguá

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 1,3" # Executa às 11:00 GMT-3 (14:00 UTC) nas segundas e quartas

jobs:
  generate-menu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/fetch-menu
        with:
          campus: Araranguá
          endpoint: gerar_cardapio_ararangua
          api-key: ${{ secrets.API_KEY }}
